### ISSUE TITLE
Trouble adding Maker.js objects?

### ISSUE THREAD

**Issue by fredklanIII** [onlfait/svg-blueprint#4]
This was inspired by MakerJs but I was curious how I would pass in a Makerjs Object? I dont see it in the docs. Thanks for doing this, its pretty surprising that Makerjs doesnt have this already.

**Comment by lautr3k** [comment]
Look at the demo https://github.com/onlfait/svg-blueprint/blob/master/demo/index.js#L15
I have to add that to the docs...
